language: python
python:
- '2.7'
install:
- pip install pycrypto
script:
- make test
- make sdist bdist
deploy:
  provider: releases
  api_key:
    secure: iXXiz94KN9yzjclDsai3gfjMVGxyUA3gxWksI9AcBRC7BiHkk8ZC3Fa7A8JWTCuaYu6TminM7+vZc/PFBzNyqo/dE9EqmORJbnL7ZJaH3X+XOlM9IfBc7kaBnx4pV2WNaNQkI38wl7SJB40PQ7LbCkfgzM9ZBYcIcHAzuq9IObk0ORCWM54cxWrx0wS4KpsmgltHSWlccH0QXmOc2cZ3yrbgpXZEAAPFd4eml376ZL0wHqoWgTpD5QcbLHuFQc6ejjGnroPKkrFn5MNYKYgvzKEnao6Zh+WGYHF4JbbUi2bz0QWT9PbgrcOelrCzs7hg3oqR2qX/IjVGajNUIN19hyLleaA6Y2v6Bi+pKE7Q9/u9UFn+a6InrxsgTgCmKTjPtzP5slI4HesrmwdY+cGlQJhMeHM+wyzf6ZQH/QFdC0lp84Dw/qfCKhMxmM4eqS7YNAHOwFbFxpI9Sn6Z5GQmWvx/oNT+CgJjgo1uvTkqIlaBP2ENM9hERcW89rWSJGUd3wq/bi0tifqVI9SM7jDG7erCQTN6qch2NXPaYF3LeM0wQeF9BVaVRJgwEAXci5MPz16YzBnf3xJqchYN/9F4nCARuB0lX1xc3yyvV/QmrgDYfKhOyddBixKZAs7iRxuscZ9imdFGRqTtrH2mYOXK3NneNAZsWlaTNg0CL9omDwY=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: 3stack-software/pdfminer
